spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:mariadb://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:iuh_ecommerce}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:long123}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=false
app.seed.enabled=${APP_SEED_ENABLED:true}
brevo.api.key=${BREVO_API_KEY:}
brevo.sender.email=dailystore6879@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=dailystore6879@gmail.com
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.jackson.deserialization.fail-on-null-for-primitives=false
